# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f38970bd6d47c3fd24ebf2e8ace4e367cf758b6ce901090953733627a238c7005a7a96d142af560bc1d3abcd908a1b45745e6064b757ce5c59e102001fc7b84c

test:
  secret_key_base: 99e4a8cc060733e79cc61bdec9380627af7c7bb32138fe6dbc89ca2527061f6fbaf272428e493cf67f2245c7b9a4400a5110c26a1effa9797b754af0e742dc77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
